/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export default class CommonConstants {

  static readonly APP_ID = ; // TODO：应用ID

  static readonly TOKEN = ; // TODO：频道鉴权令牌Token 参考readME 文档生成

  static readonly UID_ID = '123456'; // UID,用户可自行生成（在获取Token时需要）

  static readonly CHANNEL_ID = 'testChannel'; // 房间ID，用户可自行生成（在获取Token时需要）

}

